name: "Perform Makeimg"
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run'     
        required: true
        default: 'development'
      mode:
        description: 'Running mode'  
  push:
    branches: [ master ]
  schedule:
    - cron: "0 */1 * * *"
jobs:
  perform_makeimg:
    name: "Makeimg"
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
            pip install --upgrade pip
            pip install -r requirements
      - name: Running makeimg
        run: |
            python "makeimg"
        
      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Chore: Makeimg Update"
          file_pattern: "img/*"
          repository: .
          skip_fetch: false